twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        mercure_publish_url: '%env(MERCURE_PUBLISH_URL)%'
    paths:
        # point this wherever your images live
        '%kernel.project_dir%/public/uploads/pictures': images

when@test:
    twig:
        strict_variables: true
